"use client";

import { useState } from "react";
import { UploadCard } from "@/components/UploadCard";
import { ResultCard } from "@/components/ResultCard";
import { LoadingState } from "@/components/LoadingState";
import { motion, AnimatePresence } from "framer-motion";

export default function Home() {
  const [status, setStatus] = useState<"idle" | "loading" | "success" | "error">("idle");
  const [result, setResult] = useState<{ ai_generated: boolean; confidence: number } | null>(null);
  const [error, setError] = useState<string | null>(null);

  const handleUpload = async (file: File) => {
    setStatus("loading");
    setError(null);
    setResult(null);

    const formData = new FormData();
    formData.append("image", file);

    try {
      const response = await fetch("/api/detect", {
        method: "POST",
        body: formData,
      });

      if (!response.ok) {
        const errorData = await response.json();
        throw new Error(errorData.error || "Failed to analyze image");
      }

      const data = await response.json();
      setResult(data);
      setStatus("success");
    } catch (err: any) {
      setError(err.message);
      setStatus("error");
    }
  };

  return (
    <div className="max-w-4xl mx-auto px-4 md:px-6 py-12 md:py-32">
      <div className="text-center mb-12 md:mb-24">
        <motion.h1
          initial={{ opacity: 0, y: -20 }}
          animate={{ opacity: 1, y: 0 }}
          className="text-3xl md:text-6xl font-extrabold text-[#0f172a] tracking-tight mb-6 md:mb-8"
        >
          Detect AI-Generated <br className="hidden md:block" /> Images Instantly
        </motion.h1>
        <motion.p
          initial={{ opacity: 0, y: -10 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ delay: 0.1 }}
          className="text-base md:text-xl text-[#4b5563] max-w-2xl mx-auto leading-relaxed"
        >
          Upload an image to see how likely it was generated by AI.
        </motion.p>
      </div>

      <div className="space-y-8">
        <UploadCard onUpload={handleUpload} disabled={status === "loading"} />

        <AnimatePresence mode="wait">
          {status === "loading" && (
            <motion.div
              key="loading"
              initial={{ opacity: 0, scale: 0.95 }}
              animate={{ opacity: 1, scale: 1 }}
              exit={{ opacity: 0, scale: 0.95 }}
            >
              <LoadingState />
            </motion.div>
          )}

          {status === "success" && result && (
            <motion.div
              key="result"
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
            >
              <ResultCard
                isAi={result.ai_generated}
                confidence={result.confidence}
              />
            </motion.div>
          )}

          {status === "error" && (
            <motion.div
              key="error"
              initial={{ opacity: 0, y: 10 }}
              animate={{ opacity: 1, y: 0 }}
              className="p-4 rounded-2xl bg-red-50 border border-red-100 text-red-600 text-center"
            >
              <p className="font-medium">{error}</p>
              <button
                onClick={() => setStatus("idle")}
                className="text-sm underline mt-2 hover:text-red-700"
              >
                Try again
              </button>
            </motion.div>
          )}
        </AnimatePresence>
      </div>

      {/* Footer Info */}
      <div className="mt-20 pt-8 border-t border-gray-100 flex flex-col md:flex-row items-center justify-between gap-4 text-gray-400 text-[13px] font-medium">
        <div className="flex items-center gap-1.5 order-2 md:order-1">
          <span>Made by</span>
          <span className="text-gray-900">Sahil Khedkar</span>
          <span>❤️</span>
          <span className="mx-1 text-gray-200">•</span>
          <a
            href="https://x.com/sahlgo"
            target="_blank"
            rel="noopener noreferrer"
            className="flex items-center gap-1.5 hover:text-gray-900 transition-colors group"
          >
            <svg className="w-3 h-3 fill-current" viewBox="0 0 24 24" aria-hidden="true">
              <path d="M18.244 2.25h3.308l-7.227 8.26 8.502 11.24H16.17l-5.214-6.817L4.99 21.75H1.68l7.73-8.835L1.254 2.25H8.08l4.713 6.231zm-1.161 17.52h1.833L7.084 4.126H5.117z" />
            </svg>
            <span className="group-hover:underline underline-offset-4">Follow on X</span>
          </a>
        </div>

        <div className="flex gap-6 order-1 md:order-2">
          <span className="hover:text-gray-600 transition-colors cursor-pointer">Privacy Policy</span>
          <span className="hover:text-gray-600 transition-colors cursor-pointer">Terms of Service</span>
        </div>
      </div>
    </div>
  );
}
